### ISSUE TITLE
datalist->remove && controller

### ISSUE THREAD

**Issue by smartdonkeyz** [i-lateral/silverstripe-searchable#6]
in searchable.php
in the results method you use
`$results->remove($result);`
but this creates a bug that deletes stuff from the DB sometimes (because datalist->remove  remove by deleting the object [doc here](http://api.silverstripe.org/master/source-class-DataList.html#1047-1057))
this solutions seems to work since removeByID deletes from the list only
`$results->removeByID($result->ID);`

i also changed
`class SearchResults extends Controller`
to
`class SearchResults extends Page_Controller`
for a better integration in my views

**Comment by mlewis-everley** [comment]
Hi smartdonkeyz,

You are correct, but I also think manipulating a DataList in this way is not really ideal either.

Because of this I have updated the Results method (commit 1cec88406984e19d77e9c1486b005afa6aef598b) to instead provide an ArrayList (which can still be filtered, sorted, etc, but does not manipulate the database via the ORM).

**Comment by mlewis-everley** [comment]
In regards to changing the extension from SearchResults to extend Page_Controller rather than Controller, Searchable is intended to be usable in any context (to search any DataObject). Changing it to extend Page_Controller would require it to have the CMS as a dependency (so it could not be used for framework only apps).
